---
- name: set_fact realms
  set_fact:
    realms: '{{ realms | default([]) | union([item.rgw_realm]) }}'
  loop: "{{ rgw_instances_all }}"
  run_once: true

- name: create list secondary_realms
  set_fact:
    secondary_realms: "{{ secondary_realms | default([]) | union([{ 'realm': item.rgw_realm, 'endpoint': hostvars[item.host]['rgw_pull_proto'] + '://' + hostvars[item.host]['rgw_pullhost'] + ':' + hostvars[item.host]['rgw_pull_port'] | string, 'system_access_key': item.system_access_key, 'system_secret_key': item.system_secret_key, 'is_master': hostvars[item.host]['rgw_zonemaster'] }]) }}"
  loop: "{{ rgw_instances_all }}"
  run_once: true
  when: not hostvars[item.host]['rgw_zonemaster'] | bool

- name: create list zonegroups
  set_fact:
    zonegroups: "{{ zonegroups | default([]) | union([{ 'realm': item.rgw_realm, 'zonegroup': item.rgw_zonegroup, 'is_master': hostvars[item.host]['rgw_zonegroupmaster'] }]) }}"
  loop: "{{ rgw_instances_all }}"
  run_once: true
  when:
    - hostvars[item.host]['rgw_zonemaster'] | bool

- name: create list zones
  set_fact:
    zones: "{{ zones | default([]) | union([{ 'realm': item.rgw_realm, 'zonegroup': item.rgw_zonegroup, 'zone': item.rgw_zone, 'is_master': hostvars[item.host]['rgw_zonemaster'], 'system_access_key': item.system_access_key, 'system_secret_key': item.system_secret_key }]) }}"
  loop: "{{ rgw_instances_all }}"
  run_once: true

- name: create a list of dicts with each rgw endpoint and it's zone
  set_fact:
    zone_endpoint_pairs: "{{ zone_endpoint_pairs | default([]) | union([{ 'endpoint': hostvars[item.host]['rgw_multisite_proto'] + '://' + item.radosgw_address + ':' + item.radosgw_frontend_port | string, 'rgw_zone': item.rgw_zone }]) }}"
  loop: "{{ rgw_instances_all }}"
  run_once: true

- name: create string of all the endpoints in the same rgw_zone
  set_fact:
    zone_endpoints_string: "{{ zone_endpoints_string | default('') + item.endpoint + ',' }}"
  loop: "{{ zone_endpoint_pairs }}"
  when: item.rgw_zone == rgw_zone

- name: remove ',' after last endpoint in a endpoints string
  set_fact:
    zone_endpoints_string: "{{ zone_endpoints_string[:-1] }}"
  when:
    - endpoints_string is defined
    - endpoints_string[-1] == ','

- name: create a list of zones and all their endpoints
  set_fact:
    zone_endpoints_list: "{{ zone_endpoints_list | default([]) | union([{ 'endpoints': hostvars[item.host]['zone_endpoints_string'], 'zone': item.rgw_zone, 'zonegroup': item.rgw_zonegroup, 'realm': item.rgw_realm, 'is_master': hostvars[item.host]['rgw_zonemaster'] }]) }}"
  loop: "{{ rgw_instances_all }}"
  run_once: true
  when: hostvars[item.host]['zone_endpoints_string'] is defined
